### ISSUE TITLE
Examples please!

### ISSUE THREAD

**Issue by MyMakibox** [Danielhiversen/pyAmbiclimate#6]
Thanks for coding this! I was writing my own, but yours looks much more fully developed.

However, I am struggling to get it working.

Could you just give a few lines of code to show how to get setup and start making get/set calls?

**Comment by MyMakibox** [comment]
Here's what I have worked out..
---


import ambiclimate as AC
import asyncio
import aiohttp

websession = aiohttp.ClientSession()

client_id='xxxx',
client_secret='xxxx',
auth_code = 'xxxx'

OA = AC.AmbiclimateOAuth(
    client_id=client_id,
    client_secret=client_secret,
    redirect_uri='https://httpbin.org/get',
    websession=websession)

token =  await OA.get_access_token(auth_code)

print(f'Token expired? :{AC.is_token_expired(token)}')

conn = AC.AmbiclimateConnection(OA,token,websession=websession)

for device in conn.get_devices():
    print(device.name,
    await device.get_mode(),
    await device.get_sensor_temperature(),
    await device.get_sensor_humidity(),
    )

**Comment by Danielhiversen** [comment]
Here you see how it is used in Home Assistant:
https://github.com/home-assistant/core/blob/ac3a6aaa8cdb005b3c900f9d9671e5a859351060/homeassistant/components/ambiclimate/climate.py#L60
